//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGCS3.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class XplaneHil : global::System.Configuration.ApplicationSettingsBase {
        
        private static XplaneHil defaultInstance = ((XplaneHil)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new XplaneHil())));
        
        public static XplaneHil Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49003")]
        public string recPort {
            get {
                return ((string)(this["recPort"]));
            }
            set {
                this["recPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49000")]
        public string sndPort {
            get {
                return ((string)(this["sndPort"]));
            }
            set {
                this["sndPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string simIP {
            get {
                return ((string)(this["simIP"]));
            }
            set {
                this["simIP"] = value;
            }
        }
    }
}
